version: '2'
services:
    sponge_vanilla:
        image: mmonkey/sponge-vanilla
        container_name: vanilla
        ports:
            - "25565:25565"
        stdin_open: true
        tty: true
        volumes:
            - ./sponge-vanilla/data:/vanilla:rw
    sponge_forge:
        image: mmonkey/sponge-forge
        container_name: forge
        environment:
            - "PORT:25566"
        ports:
            - "25566:25566"
        stdin_open: true
        tty: true
        volumes:
            - ./sponge-forge/data:/forge:rw