version: '2'
services:
    sponge_forge:
        image: mmonkey/sponge-forge
        container_name: forge
        environment:
            - "MINECRAFT_PORT:25566"
            - "MINECRAFT_EULA:true"
            - "MINECRAFT_MAXHEAP:1024M"
            - "FORGE_VERSION:1.8.9-11.15.1.1890-1.8.9"
            - "SPONGE_VERSION:1.8.9-1890-4.2.0-BETA-1402"
        expose:
            - "25565"
        ports:
            - "25566:25566"
        stdin_open: true
        tty: true
        volumes:
            - ./sponge-forge/data:/forge:rw
    sponge_vanilla:
        image: mmonkey/sponge-vanilla
        container_name: vanilla
        environment:
            - "MINECRAFT_PORT:25567"
            - "MINECRAFT_EULA:true"
            - "MINECRAFT_MAXHEAP:1024M"
            - "SPONGE_VERSION:1.8.9-4.2.0-BETA-337"
        expose:
            - "25567"
        ports:
            - "25567:25567"
        stdin_open: true
        tty: true
        volumes:
            - ./sponge-vanilla/data:/vanilla:rw